export type InvitePosition = 'top' | 'center' | 'left' | 'right' | 'bottom';

export interface InviteSample {
  id: string;
  src: string;
  alt: string;
  occasion: string;
  position: InvitePosition;
  textColor: string;
  eyebrowColor: string;
  panel?: 'light' | 'dark';
  eyebrow: string;
  title: string;
  subtitle: string;
  line1: string;
  line2: string;
  footer: string;
}

// Placeholder copy. The artwork is generated by the lekhaAI FLUX model; in the
// real product the host fills these fields and the text is overlaid in the composer.
export const inviteSamples: InviteSample[] = [
  {
    id: 'indian-folk',
    src: '/invites/indian-folk.webp',
    alt: 'Indian folk-art wedding invitation with a golden arch and peacock',
    occasion: 'Wedding',
    position: 'center',
    textColor: '#f6ead0',
    eyebrowColor: '#e9c87a',
    eyebrow: 'Together with blessings',
    title: 'Aarav & Mira',
    subtitle: 'request the pleasure of your company',
    line1: 'Saturday, the 18th of October',
    line2: 'Sunset Garden, Jaipur',
    footer: 'RSVP by 1 October',
  },
  {
    id: 'ocean-aerial',
    src: '/invites/ocean-aerial.webp',
    alt: 'Aerial ocean and beach wedding invitation',
    occasion: 'Beach wedding',
    position: 'top',
    textColor: '#23424a',
    eyebrowColor: '#3f7c83',
    eyebrow: 'Save the date',
    title: 'Emma & James',
    subtitle: 'are getting married by the sea',
    line1: 'Friday, the 6th of June 2026',
    line2: 'Amalfi Coast, Italy',
    footer: 'RSVP by 1 May',
  },
  {
    id: 'purple-gold',
    src: '/invites/purple-gold.webp',
    alt: 'Deep purple invitation with gold filigree corners',
    occasion: 'Anniversary',
    position: 'center',
    textColor: '#f3e2bd',
    eyebrowColor: '#d9b461',
    eyebrow: 'Please join us',
    title: 'Golden Anniversary',
    subtitle: 'forty years of love — Robert & Eleanor',
    line1: 'Sunday, the 12th of July',
    line2: 'The Savoy, London',
    footer: 'RSVP by 20 June',
  },
  {
    id: 'bride-watercolor',
    src: '/invites/bride-watercolor.webp',
    alt: 'Soft watercolor bridal shower invitation',
    occasion: 'Bridal shower',
    position: 'left',
    textColor: '#3c2b22',
    eyebrowColor: '#9a7a56',
    eyebrow: 'Bridal shower',
    title: 'Celebrating Sophie',
    subtitle: 'before she says “I do”',
    line1: 'Saturday, the 9th of August, 2 PM',
    line2: 'The Garden Room',
    footer: 'RSVP by 25 July',
  },
  {
    id: 'champagne-brunch',
    src: '/invites/champagne-brunch.webp',
    alt: 'Champagne and florals brunch invitation',
    occasion: 'Engagement brunch',
    position: 'right',
    textColor: '#4a3b1f',
    eyebrowColor: '#9c7c34',
    eyebrow: 'You are invited',
    title: 'Brunch & Bubbly',
    subtitle: 'an engagement celebration',
    line1: 'Sunday, the 3rd of May, 11 AM',
    line2: 'Rose & Vine, Brooklyn',
    footer: 'RSVP by 20 April',
  },
  {
    id: 'kids-dinosaur',
    src: '/invites/kids-dinosaur.png',
    alt: 'Cute watercolor dinosaur birthday invitation',
    occasion: 'Kids birthday',
    position: 'top',
    textColor: '#4a6440',
    eyebrowColor: '#7b9268',
    eyebrow: 'Roar — you are invited',
    title: 'Lucas turns four',
    subtitle: 'a dino-mite birthday party',
    line1: 'Saturday, the 15th of March, 4 PM',
    line2: '12 Maple Lane',
    footer: 'RSVP to Mom: (555) 123-4567',
  },
  {
    id: 'kids-mario',
    src: '/invites/kids-mario.png',
    alt: 'Retro game themed kids birthday invitation',
    occasion: 'Kids birthday',
    position: 'top',
    textColor: '#1d3a5f',
    eyebrowColor: '#2f5e92',
    panel: 'light',
    eyebrow: 'Level up',
    title: 'Ethan turns nine',
    subtitle: 'a super game-day party',
    line1: 'Sunday, the 22nd of June, 3 PM',
    line2: 'The Arcade, Riverside',
    footer: 'RSVP by 15 June',
  },
];

export const heroInvite = inviteSamples[0];
export const galleryInvites = inviteSamples.slice(1);

export const heroBackInvite = inviteSamples.find((s) => s.id === 'ocean-aerial')!;
export const heroFanInvite = inviteSamples.find((s) => s.id === 'champagne-brunch')!;
export const heroThumbs = ['purple-gold', 'champagne-brunch', 'bride-watercolor', 'kids-dinosaur']
  .map((id) => inviteSamples.find((s) => s.id === id)!);
